# tutorial: https://canovasjm.netlify.app/2020/11/29/github-actions-run-a-python-script-on-schedule-and-commit-changes/

name: job_1

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *' # runs at 12:00 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py scripts
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          PRAW_CLIENT_ID: ${{ secrets.PRAW_CLIENT_ID }}
          PRAW_CLIENT_SECRET: ${{ secrets.PRAW_CLIENT_SECRET }}
          PRAW_USER_AGENT: ${{ secrets.PRAW_USER_AGENT }}
          PRAW_USERNAME: ${{ secrets.PRAW_USERNAME }}
          PRAW_PASSWORD: ${{ secrets.PRAW_PASSWORD }}
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
          LAST_FM_API_KEY: ${{ secrets.LAST_FM_API_KEY }}
          NYC_OPEN_DATA_APP_TOKEN: ${{ secrets.NYC_OPEN_DATA_APP_TOKEN }}
          
        run: | 
          python jobs/apple-app-store.py
          python jobs/freddie-mac-rates.py
          python jobs/newsapi-top-headlines.py
          python jobs/spotify-podcast-charts.py
          python jobs/kworb-scrape.py
          python jobs/last-fm-history.py
          python jobs/nyc-311-requests.py
          python jobs/s3-snapshots.py
          python jobs/mormon-reddit-submissions.py
