# tutorial: https://www.rforseo.com/ressources/launch-an-r-script-using-github-actions

name: job_test_r

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 1 *' # runs at 12:00 UTC everyday

jobs:
  build:
    runs-on: macos-latest

    # Load repo and install R
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2

    # Set up R
    - name: install packages
      run: |
        R -e 'install.packages("tidyverse")'
        R -e 'install.packages("rvest")'
        R -e 'install.packages("aws.s3")'
        R -e 'install.packages("httr")'
        R -e 'install.packages("jsonlite")'
    
    # Run script
    - name: run scripts
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      run: |
        Rscript jobs/hacker-news.r
